### ISSUE TITLE
Typo in src/bulb.js

### ISSUE THREAD

**Issue by JustAnAverageGuy** [vaibhav-1508/js_assignment#12]
Line 18 of `src/bulb.js` should read   
_'Set the "bulb" element's Image src to be the image specified by **BULB_OFF_URL**'_ , instead of 
_'Set the "bulb" element's Image src to be the image specified by **BULB_ON_URL**'_

**Comment by EshaanAgg** [comment]
@JustAnAverageGuy Do you want to work on fixing this issue?
