### ISSUE TITLE
Facing problems in the question TimespanToHumanString() in the strings.js section

### ISSUE THREAD

**Issue by Sweetdevil144** [vaibhav-1508/js_assignment#15]
I'm using the following code to determine the return statement :

function getTimePeriod(start, end) {
  const startDate = new Date(start);
  const endDate = new Date(end);
  const diff = (endDate - startDate) / 1000; // difference in seconds
  
  if (diff <= 45) {
    return "a few seconds ago";
  } else if (diff <= 90) {
    return "a minute ago";
  } else if (diff <= 45 * 60) {
    const minutes = Math.round(diff / 60);
    return `${minutes} minutes ago`;
  } else if (diff <= 90 * 60) {
    return "an hour ago";
  } else if (diff <= 22 * 60 * 60) {
    const hours = Math.round(diff / (60 * 60));
    return `${hours} hours ago`;
  } else if (diff <= 36 * 60 * 60) {
    return "a day ago";
  } else if (diff <= 25 * 24 * 60 * 60) {
    const days = Math.round(diff / (24 * 60 * 60));
    return `${days} days ago`;
  } else if (diff <= 45 * 24 * 60 * 60) {
    return "a month ago";
  } else if (diff <= 345 * 24 * 60 * 60) {
    const months = Math.round(diff / (30 * 24 * 60 * 60));
    return `${months} months ago`;
  } else if (diff <= 545 * 24 * 60 * 60) {
    return "a year ago";
  } else {
    const years = Math.round(diff / (365 * 24 * 60 * 60));
    return `${years} years ago`;
  }
}

However, the code returns wrong answers where ever the code deals with situations like '30.001" seconds or "45.001".

**Comment by EshaanAgg** [comment]
Closing this issue now as implementations that work well with the existing test cases have been implemented by other freshers.
