### ISSUE TITLE
One of the ArrayTests is incorrect. 

### ISSUE THREAD

**Issue by JustAnAverageGuy** [vaibhav-1508/js_assignment#6]
![image](https://user-images.githubusercontent.com/68919330/230769114-b17c0c5c-856e-4314-9a6a-98bb9123dd4e.png)
The second attached test is wrong.

**Comment by brf153** [comment]
Even I think so.

**Comment by brf153** [comment]
I have changed the values in my file. Should I make a PR for it?
![Screenshot (33)](https://user-images.githubusercontent.com/107868772/230771249-0b21e016-6f53-45bb-9090-93713825adca.png)

**Comment by EshaanAgg** [comment]
Hey guys! Great work. The test cases were indeed wrong and have been updated. Thanks for bringing the same into our notice.

Closing the issue as completed.
