### ISSUE TITLE
Wrong tests in number module 

### ISSUE THREAD

**Issue by JustAnAverageGuy** [vaibhav-1508/js_assignment#8]
![image](https://user-images.githubusercontent.com/68919330/230772524-591ed078-005c-4153-a064-46771ada1b46.png)
instead of `getRectangleArea`, it should be `getAverage`

**Comment by Sweetdevil144** [comment]
Issue is fixed now.

**Comment by Sweetdevil144** [comment]
I think so

**Comment by EshaanAgg** [comment]
Issue has been fixed. Thanks for your inputs!
